-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id text PRIMARY KEY,
    first_name text,
    last_name text,
    password_hash text NOT NULL,
    email text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_pkey ON users(id text_ops);
CREATE INDEX email_idx ON users(email text_ops);
